name: test_tool_flutter
description: A new flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ^2.0.1
  common_dart_core:
    path: ../../common_dart_core

dev_dependencies:

